server:
  port: 8082

spring:
  security:
    user:
      name: angshit
      password: angshit
      roles: ADMIN,USER  
  
security:
  oauth2:
    client:
      client-id: desk
      client-secret: pin
      access-token-validity-seconds: 3600
      authorized-grant-types: refresh_token,authorization_code,password,client_credentials
      scope: READ,WRITE
    authorization:
      check-token-access: permitAll  
